---
- name: Deploy PetClinic App
  hosts: blue
  become: yes

  tasks:
  - name: Change permissions for mvnw file
    file:
      path: /home/ubuntu/app/mvnw
      owner: ubuntu
      group: ubuntu
      mode: "0775"

  - name: Convert mvnw file to UNIX format
    shell:
      cmd: dos2unix mvnw
      chdir: /home/ubuntu/app

  - name: Install wrapper
    shell: 
      cmd: mvn -N io.takari:maven:wrapper
      chdir: /home/ubuntu/app

  - shell:
      cmd: mvn spring-javaformat:apply
      chdir: /home/ubuntu/app
  
 - name: Deploy app
    shell:
      cmd: mvn spring-boot:run -Dcheckstyle.skip -Dspring-boot.run.profiles=mysql > /dev/null 2>&1 &
      chdir: /home/ubuntu/app
    async: 10
    poll: 0