---
- name: Pull source code for Petclinic from github
  hosts: blue
  become: yes

  tasks:
  - name: Install git
    apt:
      name: git
      state: latest
      update_cache: yes
    notify: git version

  - name: Pull repo
    git:
    repo: https://github.com/unicum0212/petclinic-java.git
    dest: /home/ubuntu/app